# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "f/Yeao2xMqNcV/TK9bKgPoPx/OL1kz8zoQw3dWYcteORH1lpEXEAYHotEA+ph7jgqZS8Pwcx5Xb19yfEVBHVvUjEYP8dvRwGp0QKb1nCWM9uK7jQvF/zZAmWY/t+JpRZdmQEJrBIdsU+u6oBbOsdoGTTt3Z6i57Kf5EmopB2O+BwZKUMKJQSVor1KzQjj4DpxyNsHLzzPu5MaJNozr/t56aqwfTrKX8O4J+GWQLEITuohcIVaJoIeXDtc9EQ3zqYEp9sUIOyox/t7pT4rmoXmrbruPy8GK7EyZegafMzCqTb+bEX0Cna6c7Ql1Yyc30e4nOAEbH/c3BHTmPmUZi3GJtfgf+UpvWQm3knywLejtePHsrnIJhldyXnxu+LQuL+E5GHEku9Vrkm/UJAVSneeP+5BbKpjwS0gTc1U+Cjq/fLhG6POvNcJ2xhwNM/HbqNdz18Xav+WnMOJfNFir34EUSW1Rg5+fKja1bQqdJ+F570Sx8Xdmu2GY+EoSIuqpDTFcGNEBmP782LT9L63ihFWTd2iQNRuAJ5J0pb1dyiiJvXHAAx9mBNhY2EyCzSvYY0/0GmUuQTMEmrrPWVrMQuc/cqkM7CJvZJAonMxD+xsgFJRsISigG33LV9GLDHYjRRuWkugYtmePD/eZw0ulAEQNiWyL19xu6b8py6/Mtthwk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
