travis:
  secure:
    BINSTAR_TOKEN: f/Yeao2xMqNcV/TK9bKgPoPx/OL1kz8zoQw3dWYcteORH1lpEXEAYHotEA+ph7jgqZS8Pwcx5Xb19yfEVBHVvUjEYP8dvRwGp0QKb1nCWM9uK7jQvF/zZAmWY/t+JpRZdmQEJrBIdsU+u6oBbOsdoGTTt3Z6i57Kf5EmopB2O+BwZKUMKJQSVor1KzQjj4DpxyNsHLzzPu5MaJNozr/t56aqwfTrKX8O4J+GWQLEITuohcIVaJoIeXDtc9EQ3zqYEp9sUIOyox/t7pT4rmoXmrbruPy8GK7EyZegafMzCqTb+bEX0Cna6c7Ql1Yyc30e4nOAEbH/c3BHTmPmUZi3GJtfgf+UpvWQm3knywLejtePHsrnIJhldyXnxu+LQuL+E5GHEku9Vrkm/UJAVSneeP+5BbKpjwS0gTc1U+Cjq/fLhG6POvNcJ2xhwNM/HbqNdz18Xav+WnMOJfNFir34EUSW1Rg5+fKja1bQqdJ+F570Sx8Xdmu2GY+EoSIuqpDTFcGNEBmP782LT9L63ihFWTd2iQNRuAJ5J0pb1dyiiJvXHAAx9mBNhY2EyCzSvYY0/0GmUuQTMEmrrPWVrMQuc/cqkM7CJvZJAonMxD+xsgFJRsISigG33LV9GLDHYjRRuWkugYtmePD/eZw0ulAEQNiWyL19xu6b8py6/Mtthwk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
