travis:
  secure:
    BINSTAR_TOKEN: UG5twDGYMl/Rj7h2w0Pse7cUzAHczVywfTyvyF+/2hD0kc+qHL1/7PtAw6tFVhP3jXaWGqH2yqV9QM9R6kTKiljWW8xRdOUcyvY9T5Lo/xRCGMDKmR/MkbYxFnTG0sQqxyxkf401d8QdFGxt8cVy9P0Vf/+wo8aCW5WMFp/jysBJJz8YJ8sHpIZrny6pBkvy4SPyCrHKYP6XGuFGvshJdNoSC5P//Rh9IF/srZsVGXKq/WAm8wBl3Tjv1v2CZlsgR7ciAlbmrdBm2lxrTiGO94pQE8e+cbSR2PXene1SdAzJCV1mQhyH2IG2YCmJHKg0a90gD/u8rx6Sepdj6ICnMWh7D9FEN1wotX/3PGYmukaNJBrkoKK+6M3Qw7/R42ROHAZ0qTqTFmNjMyZQ/La7NxO4+Ox2peP72LUjg/hXT9Lu0EXJSstwx6SKM1IVmRsgBpUE7CwEq9mohCv5OPNvXU73dL25rMtc4bUGvDD1FZCOxGLwTaSCQHxjfiFzw7CpL4YwNqWUHa3flOSZHxrr6bW5wa+AAu+/k9RWS9bVx8dYlvzamsWb35RNZMvk1c+Y47Wn94iZtqe+E2dq053UWL4Ms8lPBZsN6IdQrk7nCzgzyAap0IU9KvO2DsTqn7cQ08GtlKuyUGZvWq0oHU9QFiWxeRVtggiXyeWkm2kLh/s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
